#! /bin/sh

ntrain=50

corpus=$1

if [ ! '(' -d $corpus/ham -a -d $corpus/spam ')' ]; then
    echo $corpus does not look like a corpus: ham/, spam/, or both missing >&2
    exit 1
fi

bf=$(pwd)/bfilter
make $bf

if [ ! -x $bf ]; then
    echo $bf is not executable >&2
    exit 1
fi

export BFILTER_DB=$(mktemp -u)
echo $BFILTER_DB

cd $corpus/spam
nspam=$(ls | wc -l)
mspam=$(echo $nspam / $ntrain | bc)

for m in $(ls | awk "NR % $mspam == 0 { print }"); do
    echo $m
    $bf isspam < $m
done

cd $corpus/ham
nham=$(ls | wc -l)
mham=$(echo $nham / $ntrain | bc)

for m in $(ls | awk "NR % $mham == 0 { print }"); do
    echo $m
    #if [ $m = '1404241811.531.hydrogen.mv6.co.uk' ]; then exit 1; fi
    $bf isreal < $m
done

cd $corpus/spam
out=$(mktemp)
for m in $(ls | sed 50q); do
    $bf test < $m # 2>/dev/null
done > $out
right=$(grep -c spam $out)
echo right $right
wrong=$(grep -c real $out)
echo wrong $wrong
unsure=$(grep -c UNSURE $out)
echo unsure $unsure
pspam=$(echo "scale=2; $right * 100 / ($right + $wrong + $unsure)" | bc)
pspamu=$(echo "scale=2; $unsure * 100 / ($right + $wrong + $unsure)" | bc)
rm $out

cd $corpus/ham
out=$(mktemp)
for m in $(ls | sed 50q); do
    $bf test < $m # 2>/dev/null
done > $out
right=$(grep -c real $out)
echo right $right
wrong=$(grep -c spam $out)
echo wrong $wrong
unsure=$(grep -c UNSURE $out)
echo unsure $unsure
pham=$(echo "scale=2; $right * 100 / ($right + $wrong + $unsure)" | bc)
phamu=$(echo "scale=2; $unsure * 100 / ($right + $wrong + $unsure)" | bc)
rm $out

echo
echo "ham: $pham% correct, $phamu% unsure; spam: $pspam% correct, $pspamu% unsure"
ls -l $BFILTER_DB
